### ISSUE TITLE
How to close the application?

### ISSUE THREAD

**Issue by Supernova1024** [iPzard/electron-react-python-template#50] opened 2022-11-29 07:13 UTC
I can't close the application.
There is a function to close the flask app in the backend code.
But it doesn't work.
I want to close the whole application: ReactJs and Flask.

**Comment by iPzard** [comment] 2022-11-30 23:17
Thanks for sharing this, would you mind providing the steps to reproduce this, as well as your OS? It seems to be closing fine on my end (Windows 10) and closing when I close the app.

**Comment by Supernova1024** [comment] 2022-12-01 05:47
I am working on Windows 10.
Yeah, The app is closed when I click "close" icon on top bar
But I mean I want to close the whole application by clicking a new button called "Quit".
The button will look like "add amount" and it will be placed in the main section rather than top bar

**Closed** 2023-05-01 13:40 UTC
Labels: bug 🦟, wontfix
