### ISSUE TITLE
GET requests fail when building the application for MacOS

### ISSUE THREAD

**Issue by ivanlori** [iPzard/electron-react-python-template#16] opened 2021-04-26 05:31 UTC
Hi,
In development mode I have done GET requests and they work but fail when building the application for MacOS.
I haven't tried building windows file.

**Comment by iPzard** [comment] 2021-05-04 03:44
Hello, I don't have a Mac computer I can use at the moment to test this.. There are likely some changes needed to `packageMacOS` in `[scripts/package.js](https://github.com/iPzard/electron-react-python-template/blob/master/scripts/package.js)' I'm open to pull requests if you make an update that fixes it (or even post here and I can make updates from there).

**Comment by ivanlori** [comment] 2021-05-05 20:13
I don't know where is the problem in the code related to the failed request from axios to python API. In dev mode it works but after build not. So I was hoping in your help 🙂

**Comment by iPzard** [comment] 2021-05-06 04:50
Sure, I can take a look! But not sure when I'll have access to a mac, so might take a little while.

**Comment by iPzard** [comment] 2021-05-26 01:26
@ivanlori do you have a repo you can share where the issue is happening?

**Comment by ivanlori** [comment] 2021-05-27 05:10
@iPzard unfortunately I haven't the repo public with that issue

**Comment by iPzard** [comment] 2021-05-27 05:18
Ok gotcha, I think this might be from line 159 in `main.js`
![Untitled](https://user-images.githubusercontent.com/8584126/119769497-67f9bf00-be6f-11eb-9177-e6e749fe3acd.png)

When you run `yarn run build:package:mac`, a `/resources/*` directory will be created, does a `/resources/app/app.exe` exist, or is it `/resources/app/app.app` maybe? Or what do you see, when you get a chance.. If you're still working on this project.

**Comment by ivanlori** [comment] 2021-06-02 14:54
Hi,
no I don't see any .exe file in the resources/ 
<img width="267" alt="Screenshot 2021-06-02 at 16 51 34" src="https://user-images.githubusercontent.com/7620920/120502706-f10a7c00-c3c2-11eb-99c5-6b0e0b83aae2.png">
and even into the dist/ folder seems all ok
<img width="267" alt="Screenshot 2021-06-02 at 16 53 24" src="https://user-images.githubusercontent.com/7620920/120502932-22834780-c3c3-11eb-982d-e9badc57ad3d.png">

**Comment by iPzard** [comment] 2021-06-02 15:23
If you open a terminal in the `resources` directory and type `open ./app.app 3000` (without quotes) and hit enter, does your app launch and run as expected?

**Comment by ivanlori** [comment] 2021-06-02 15:30
It says the file doesn't exist, the content of the app folder is attached
<img width="267" alt="Screenshot 2021-06-02 at 17 29 07" src="https://user-images.githubusercontent.com/7620920/120508634-2cf41000-c3c8-11eb-9896-d6639b5fc2ce.png">
<img width="267" alt="Screenshot 2021-06-02 at 17 29 20" src="https://user-images.githubusercontent.com/7620920/120508645-2ebdd380-c3c8-11eb-997a-08e81c90d326.png">

**Comment by iPzard** [comment] 2021-06-02 15:36
Sorry.. realized that shortly after posting. I think I see what the problem is though. In `main.js` it's calling:
`spawn(`start ./resources/app/app.exe ${port}`, { detached: false, shell: true, stdio: 'pipe' });`

But I believe for mac this should be:
`spawn(`start ./resources/app/app.app ${port}`, { detached: false, shell: true, stdio: 'pipe' });`

Then you'd need to repackage and try.. If that's doesn't work, I can try to get a MacOS virtual machine set up tonight to debug it further.

**Comment by ivanlori** [comment] 2021-06-02 15:53
I've tried both with /app.app and just /app because as I see from the details of this file it doesn't have any extension but it is an executable. :/
Anyway should be here the problem, your suggestion makes sense.

**Comment by iPzard** [comment] 2021-06-03 00:58
Got a macOS virtual environment set up, just working out some of the kinks.. gonna try replacing the production script with the following and see if that helps, will update here. 

'''
  const appFile = process.platform === 'darwin' ? 'app.app' : 'app.exe';
  spawn(`start ./resources/app/${appFile} ${port}`, { detached: false, shell: true, stdio: 'pipe' });
'''

**Comment by iPzard** [comment] 2021-06-04 06:47
Great news @ivanlori ! Was able to get a Virtualbox set up with macOS (Big Sur), took longer than I'd have liked but was able to get everything working as expected to where REST calls are successfully made. I've pushed the changes, if you're using an older version of the repo, the fixes were applied in this (somewhat small) commit, so you can just copy over the relevant parts. 

https://github.com/iPzard/electron-react-python-template/commit/a979fb130757a05cefd4ba4661179ee48752b754

Gonna close the ticket since it's fixed now, but if you still have issues feel free to re-open or open another.

**Closed by iPzard** 2021-06-04 06:47 UTC
Labels: enhancement ✨, help wanted 🦮
